
<#--username input-->
<div class="form-group row">
    <label class="col-sm-2 col-form-label">Username:</label>
    <div class="col-sm-6">
        <input type="text" name="username" class="form-control" placeholder="Username"/>
    </div>
</div>
<#--password input-->
<div class="form-group row">
    <label class="col-sm-2 col-form-label">Password:</label>
    <div class="col-sm-6">
        <input type="password" name="password" class="form-control" placeholder="Password"/>
    </div>
</div>